Teste SKA/Models/ErrorViewModel.cs
namespace Teste_SKA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Teste SKA/Models/Tarefa.cs
namespace Teste_SKA.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public bool Concluida { get; set; }
    }
}

Teste SKA/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.Diagnostics;
using System.Text.Json;
using Teste_SKA.Models;

namespace Teste_SKA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Teste SKA/Controllers/TarefaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Teste_SKA.Models;

[Route("api/[controller]")]
public class TarefaController : ControllerBase
{
    private static List<Tarefa> tarefas = new List<Tarefa>();

    [HttpGet]
    public IActionResult GetTarefas()
    {
        return Ok(tarefas);
    }

    [HttpPost]
    public IActionResult AdicionarTarefa([FromBody] Tarefa tarefa)
    {
        tarefa.Id = tarefas.Count + 1;
        tarefas.Add(tarefa);
        return Ok(tarefa);
    }

    [HttpPost("MarcarConcluida/{id}")]
    public IActionResult MarcarTarefaConcluida(int id)
    {
        var tarefa = tarefas.FirstOrDefault(t => t.Id == id);
        if (tarefa == null)
        {
            return NotFound();
        }

        tarefa.Concluida = true;
        return Ok(tarefa);
    }

    [HttpDelete("RemoverTarefa/{id}")]
    public IActionResult RemoverTarefa(int id)
    {
        var tarefa = tarefas.FirstOrDefault(t => t.Id == id);
        if (tarefa == null)
        {
            return NotFound();
        }

        tarefas.Remove(tarefa);
        return Ok(tarefa);
    }
}

Teste SKA/Views/Home/Index.cshtml
<div class="container" >
    <div class="row" id="divBody">
        <div class="col-sm-12 col-md-5 col-12"  id="divInput">
            <h1>To do list</h1>
            <form>
               <div id="divForm">
                    <label>Titulo</label>
                    <input id="inputTituloTarefa" class="col-sm-10 col-md-8 col-8" type="text" />
               </div>
                <div id="divForm">
                    <label>Descrição</label>
                    <input id="inputDescricaoTarefa" class="col-sm-10 col-md-8 col-8" type="text" />
                    <img src="~/images/mais.png" onclick="InputTarefa()" />
               </div>
            </form>
        </div>
        <ul id="divUl">
        </ul>
   </div>
</div>


<script>

    function InputTarefa() {
        let inputTituloTarefa = $("#inputTituloTarefa").val()
        let inputDescricaoTarefa = $("#inputDescricaoTarefa").val()
        $("#inputTituloTarefa").val('')
        $("#inputDescricaoTarefa").val('')
            $.ajax({
                method: "POST",
                dataType: 'json',
                contentType: 'application/json',
            url: "@(Url.Action("AdicionarTarefa", "Tarefa"))",
                data: JSON.stringify({
                    titulo: inputTituloTarefa,
                    descricao: inputDescricaoTarefa
                }),
                success: function (data) {
                BuscarTarefas()
                },
                error: function (params) {
                    console.log("error")
                    console.log(params)
                }
            });
        
    }
    BuscarTarefas()
    function BuscarTarefas() {
        $.ajax({
            method: "GET",
            dataType: 'json',
            contentType: 'application/json',
            url: "@(Url.Action("GetTarefas", "Tarefa"))",
            data: JSON.stringify({
                titulo: inputTituloTarefa,
                descricao: inputDescricaoTarefa
            }),
            success: function (data) {
                console.log(data)
                $("#divUl").html(` <ul id="divUl"></ul>`)
                for (let i = 0; i < data.length; i++) {
                    if (data[i].concluida == true) {
                        $("#divUl").append(` <li class="col-sm-12 col-12 col-md-5" id="divTask"><input  class="form-check-input" type="checkbox" value="" onchange="ConcluirTarefa(${data[i].id})" checked id="flexCheckDefault">${data[i].titulo} - ${data[i].descricao}<img src="images/lixeira.png" onclick="DeletarTarefa(${data[i].id})" /></li>`)
                    }else{
                        $("#divUl").append(` <li class="col-sm-12 col-12 col-md-5" id="divTask"><input  class="form-check-input" type="checkbox" value="" onchange="ConcluirTarefa(${data[i].id})" id="flexCheckDefault">${data[i].titulo} - ${data[i].descricao}<img src="images/lixeira.png" onclick="DeletarTarefa(${data[i].id})" /></li>`)
                    }
                    
                }
            },
            error: function (params) {
                console.log("error")
                console.log(params)
            }
        });
    }

    function DeletarTarefa(id){
        console.log(id)
        $.ajax({
            url: "/api/Tarefa/RemoverTarefa/" + id,
            type: "DELETE",
            success: function (data) {
                BuscarTarefas()
            },
            error: function (xhr, status, error) {
                console.log("Erro ao remover tarefa:", status, error);
            }
        });
    }

    function ConcluirTarefa(id) {
        console.log(id)
        $.ajax({
            url: "/api/Tarefa/MarcarConcluida/" + id,
            type: "POST",
            success: function (data) {
                BuscarTarefas()
            },
            error: function (xhr, status, error) {
                console.log("Erro ao remover tarefa:", status, error);
            }
        });
    }

</script>

Teste SKA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]SKA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Teste_SKA.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SKA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      @*   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Teste_SKA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>